//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal_Medication_Care
    {
        public System.Guid Animal_ID { get; set; }
        public string medication { get; set; }
        public string Vaccine { get; set; }
        public string dose { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public string vet { get; set; }
        public string description { get; set; }
        public int Record_ID { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
