//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Attraction
    {
        public Attraction()
        {
            this.BoxOffice_Records = new HashSet<BoxOffice_Records>();
            this.Employees = new HashSet<Employee>();
        }
        [DisplayName("Attraction Name")]
        public string attraction_name { get; set; }
        public System.Guid manager_ID { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.Guid> Exhibit_ID { get; set; }
        public System.Guid Attraction_ID { get; set; }
        public string manager_name { get; set; }
        public virtual Exhibit Exhibit { get; set; }
        public virtual ICollection<BoxOffice_Records> BoxOffice_Records { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
