//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxOffice_Records
    {
        public Nullable<decimal> membership_discount { get; set; }
        public Nullable<System.Guid> Customer_ID { get; set; }
        public Nullable<System.Guid> Attraction_ID { get; set; }
        public System.Guid Department_ID { get; set; }
        public int quantity { get; set; }
        public decimal tot_amt_paid_after_discounts { get; set; }
        public System.DateTime date { get; set; }
        public System.Guid Sale_ID { get; set; }
        public Nullable<int> Ticket_type_ID { get; set; }
    
        public virtual Attraction Attraction { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Department Department { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
