//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Customer
    {
        public Customer()
        {
            this.BoxOffice_Records = new HashSet<BoxOffice_Records>();
            this.Shop_Sale_Record = new HashSet<Shop_Sale_Record>();
        }
        [DisplayName("First Name")]
        public string f_name { get; set; }
        public string mid_init { get; set; }
        [DisplayName("Last Name")]
        public string l_name { get; set; }
        [DisplayName("Phone Number")]
        public string phone_number { get; set; }
        public bool membership { get; set; }
        public System.Guid Customer_ID { get; set; }
    
        public virtual ICollection<BoxOffice_Records> BoxOffice_Records { get; set; }
        public virtual ICollection<Shop_Sale_Record> Shop_Sale_Record { get; set; }
    }
}
