//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class team4zooEntities : DbContext
    {
        public team4zooEntities()
            : base("name=team4zooEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Animal> Animals { get; set; }
        public DbSet<Animal_Feed_Care> Animal_Feed_Care { get; set; }
        public DbSet<Animal_Medication_Care> Animal_Medication_Care { get; set; }
        public DbSet<Attraction> Attractions { get; set; }
        public DbSet<BoxOffice_Records> BoxOffice_Records { get; set; }
        public DbSet<Credential> Credentials { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Exhibit> Exhibits { get; set; }
        public DbSet<Family_Name> Family_Name { get; set; }
        public DbSet<Food_Purchases> Food_Purchases { get; set; }
        public DbSet<Food_Supply> Food_Supply { get; set; }
        public DbSet<Inventory> Inventory { get; set; }
        public DbSet<Job> Jobs { get; set; }
        public DbSet<Maintenance> Maintenances { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Shop_Sale_Record> Shop_Sale_Record { get; set; }
        public DbSet<Shop> Shops { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<Zoo> Zoos { get; set; }
        public DbSet<sysdiagram1> sysdiagram1 { get; set; }
    }
}
