//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.BoxOffice_Records = new HashSet<BoxOffice_Records>();
            this.Employees = new HashSet<Employee>();
            this.Food_Purchases = new HashSet<Food_Purchases>();
            this.Shops = new HashSet<Shop>();
        }
    
        public string department_name { get; set; }
        public string zoo_name { get; set; }
        public System.Guid Department_ID { get; set; }
        public decimal dep_revenue { get; set; }
        public Nullable<System.Guid> Supervisor_ID { get; set; }
        public decimal dep_expenditure { get; set; }
    
        public virtual ICollection<BoxOffice_Records> BoxOffice_Records { get; set; }
        public virtual Zoo Zoo { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Food_Purchases> Food_Purchases { get; set; }
        public virtual ICollection<Shop> Shops { get; set; }
    }
}
