//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    


    public partial class Employee
    {
        public Employee()
        {
            this.Animal_Medication_Care = new HashSet<Animal_Medication_Care>();
            this.Maintenances = new HashSet<Maintenance>();
            this.Animals = new HashSet<Animal>();
        }
        [DisplayName("First Name")]
        public string f_name { get; set; }
        public string mid_init { get; set; }
        [DisplayName("Last Name")]
        public string l_name { get; set; }
        public string email { get; set; }
        public string sex { get; set; }
        public System.DateTime dob { get; set; }
        public string ssn { get; set; }
        public decimal hourly_wage { get; set; }
        public System.DateTime hire_date { get; set; }
        public Nullable<int> sick_days { get; set; }
        public string phone_num { get; set; }
        public bool isActive { get; set; }
        public System.Guid Employee_ID { get; set; }
        public Nullable<System.Guid> Attraction_ID { get; set; }
        public Nullable<System.Guid> Department_ID { get; set; }
        public string username { get; set; }
        public Nullable<System.Guid> Role_ID { get; set; }
        public string display_name { get; set; }
        public Nullable<System.Guid> Supervisor_ID { get; set; }
    
        public virtual ICollection<Animal_Medication_Care> Animal_Medication_Care { get; set; }
        public virtual Attraction Attraction { get; set; }
        public virtual Credential Credential { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Maintenance> Maintenances { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Animal> Animals { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Employee Employee11 { get; set; }
        public virtual Employee Employee3 { get; set; }
        public virtual Employee Employee12 { get; set; }
        public virtual Employee Employee4 { get; set; }
    }
}
