//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibit
    {
        public Exhibit()
        {
            this.Animals = new HashSet<Animal>();
            this.Attractions = new HashSet<Attraction>();
            this.Maintenances = new HashSet<Maintenance>();
        }
    
        public System.Guid Exhibit_ID { get; set; }
        public string exhibit_loc { get; set; }
        public string exhibit_name { get; set; }
        public string zoo_name { get; set; }
        public bool isOpen { get; set; }
    
        public virtual ICollection<Animal> Animals { get; set; }
        public virtual ICollection<Attraction> Attractions { get; set; }
        public virtual Zoo Zoo { get; set; }
        public virtual ICollection<Maintenance> Maintenances { get; set; }
    }
}
