//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family_Name
    {
        public Family_Name()
        {
            this.Animals = new HashSet<Animal>();
        }
    
        public string family_title { get; set; }
        public int Family_ID { get; set; }
    
        public virtual ICollection<Animal> Animals { get; set; }
    }
}
