//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_Purchases
    {
        public int order_ID { get; set; }
        public string Food_type { get; set; }
        public System.DateTime date { get; set; }
        public decimal amount_purchased { get; set; }
        public decimal tot_cost { get; set; }
        public System.Guid Department_ID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Food_Supply Food_Supply { get; set; }
    }
}
