//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_Supply
    {
        public Food_Supply()
        {
            this.Food_Purchases = new HashSet<Food_Purchases>();
            this.Animals = new HashSet<Animal>();
        }

        public decimal quantity_fed { get; set; }
        public string Food_type { get; set; }
        public System.DateTime last_ordered { get; set; }
        public Nullable<System.DateTime> resupply_date { get; set; }
    
        public virtual ICollection<Food_Purchases> Food_Purchases { get; set; }
        public virtual ICollection<Animal> Animals { get; set; }
        public string ErrorMessage { get; set; }
        public override string ToString()
        {
            return this.Food_type;
        }
    }
}
