//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public System.Guid Ticket_ID { get; set; }
        public int job_type { get; set; }
        public System.Guid Employee_ID { get; set; }
        public System.DateTime due_date { get; set; }
        public Nullable<System.Guid> Exhibit_ID { get; set; }
        public bool status { get; set; }
        public string description { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Exhibit Exhibit { get; set; }
    }
}
