//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Shop_Sale_Record
    {
        public System.Guid Sale_ID { get; set; }
        public System.Guid Shop_ID { get; set; }
        public System.Guid Item_ID { get; set; }
        public int quantity { get; set; }
        public System.Guid Customer_ID { get; set; }
        [DisplayName("Refund")]
        public bool refund_flag { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
