//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.BoxOffice_Records = new HashSet<BoxOffice_Records>();
        }
    
        public int Ticket_type_ID { get; set; }
        public string Ticket_type { get; set; }
    
        public virtual ICollection<BoxOffice_Records> BoxOffice_Records { get; set; }
    }
}
