//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zoo
    {
        public Zoo()
        {
            this.Departments = new HashSet<Department>();
            this.Exhibits = new HashSet<Exhibit>();
        }
    
        public string zoo_name { get; set; }
        public int zoo_acres { get; set; }
        public System.DateTime zoo_est_date { get; set; }
    
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Exhibit> Exhibits { get; set; }
    }
}
